import { Benefit } from "@/types/benefit"

export const mockBenefits: Benefit[] = [
  {
    id: "santander-avatar-sushi",
    providerSlug: "santander",
    bankName: "Santander",
    merchantName: "Avatar Sushi",
    merchantCanonicalName: "Avatar Sushi",
    merchantSlug: "avatar-sushi",
    categoryName: "Comida",
    title: "30% de descuento en Avatar Sushi pagando con tarjetas Santander",
    benefitType: "discount",
    benefitValue: 30,
    benefitValueUnit: "percentage",
    days: ["Lunes", "Martes"],
    channel: "ambos",
    paymentMethods: ["Crédito", "Débito"],
    capAmount: 12000,
    termsText:
      "Válido en locales adheridos y compras directas. No acumulable con otras promociones. Excluye agregadores externos.",
    sourceUrl: "https://example.com/santander-avatar-sushi",
    confidenceScore: 0.94,
    validationStatus: "validated",
    validUntil: "2026-05-31",
    lastUpdated: "2026-04-14",
    summary: "Ideal para salidas de inicio de semana con tope visible y cobertura presencial u online directa.",
    conditions: [
      "Aplica pagando directamente en la caja o sitio oficial del comercio.",
      "No aplica para compras vía marketplaces o gift cards.",
      "Tope mensual por cliente.",
    ],
    featuredTag: "Mejor hoy",
  },
  {
    id: "bci-jumbo",
    providerSlug: "bci",
    bankName: "Bci",
    merchantName: "Jumbo",
    merchantCanonicalName: "Jumbo",
    merchantSlug: "jumbo",
    categoryName: "Supermercados",
    title: "25% de descuento en Jumbo con tarjetas Bci",
    benefitType: "discount",
    benefitValue: 25,
    benefitValueUnit: "percentage",
    days: ["Miércoles"],
    channel: "presencial",
    paymentMethods: ["Crédito"],
    capAmount: 20000,
    termsText:
      "Válido en compras presenciales en supermercados Jumbo adheridos. Tope por mes calendario.",
    sourceUrl: "https://example.com/bci-jumbo",
    confidenceScore: 0.91,
    validationStatus: "validated",
    validUntil: "2026-06-30",
    lastUpdated: "2026-04-13",
    summary: "Uno de los descuentos más agresivos en supermercado, con foco claro en compra grande semanal.",
    conditions: [
      "Solo pagos con tarjetas de crédito Bci.",
      "Excluye tabaco, recargas, gift cards y servicios financieros.",
      "Tope de abono mensual por RUT.",
    ],
    featuredTag: null,
  },
  {
    id: "banco-chile-cruz-verde",
    providerSlug: "banco-de-chile",
    bankName: "Banco de Chile",
    merchantName: "Cruz Verde",
    merchantCanonicalName: "Cruz Verde",
    merchantSlug: "cruz-verde",
    categoryName: "Farmacias",
    title: "40% de descuento en Cruz Verde con tarjetas del Banco de Chile",
    benefitType: "discount",
    benefitValue: 40,
    benefitValueUnit: "percentage",
    days: ["Lunes"],
    channel: "ambos",
    paymentMethods: ["Crédito", "Débito"],
    capAmount: 15000,
    termsText:
      "Válido en productos seleccionados y compras con enrolamiento digital activo.",
    sourceUrl: "https://example.com/bchile-cruzverde",
    confidenceScore: 0.88,
    validationStatus: "monitoring",
    validUntil: "2026-04-30",
    lastUpdated: "2026-04-12",
    summary: "Farmacia con alto porcentaje de ahorro, aunque conviene revisar exclusiones por laboratorio.",
    conditions: [
      "Excluye medicamentos con receta retenida y convenios.",
      "Aplica en app, web y locales adheridos.",
      "Tope mensual total por cliente.",
    ],
    featuredTag: null,
  },
  {
    id: "falabella-starbucks",
    providerSlug: "banco-falabella",
    bankName: "Banco Falabella",
    merchantName: "Starbucks",
    merchantCanonicalName: "Starbucks",
    merchantSlug: "starbucks",
    categoryName: "Comida",
    title: "30% de descuento en Starbucks con CMR",
    benefitType: "discount",
    benefitValue: 30,
    benefitValueUnit: "percentage",
    days: ["Jueves"],
    channel: "ambos",
    paymentMethods: ["Crédito", "Prepago"],
    capAmount: 8000,
    termsText:
      "Beneficio válido en compras presenciales y mobile order donde el comercio lo permita.",
    sourceUrl: "https://example.com/falabella-starbucks",
    confidenceScore: 0.86,
    validationStatus: "validated",
    validUntil: "2026-05-15",
    lastUpdated: "2026-04-11",
    summary: "Muy competitivo para consumo frecuente, aunque con tope acotado.",
    conditions: [
      "No acumulable con refill ni promociones internas.",
      "Tope mensual por cliente.",
      "Aplican locales adheridos.",
    ],
    featuredTag: null,
  },
  {
    id: "scotia-copec",
    providerSlug: "scotiabank",
    bankName: "Scotiabank",
    merchantName: "Copec",
    merchantCanonicalName: "Copec",
    merchantSlug: "copec",
    categoryName: "Combustible",
    title: "7% de cashback en Copec con Scotiabank",
    benefitType: "cashback",
    benefitValue: 7,
    benefitValueUnit: "percentage",
    days: ["Viernes", "Sábado", "Domingo"],
    channel: "presencial",
    paymentMethods: ["Crédito"],
    capAmount: 10000,
    termsText:
      "Cashback en estado de cuenta dentro de 10 días hábiles. Válido en estaciones adheridas.",
    sourceUrl: "https://example.com/scotia-copec",
    confidenceScore: 0.82,
    validationStatus: "monitoring",
    validUntil: "2026-07-31",
    lastUpdated: "2026-04-13",
    summary: "Menor porcentaje que otras categorías, pero útil por recurrencia y vigencia extensa.",
    conditions: [
      "No incluye compras en tienda Pronto.",
      "Tope acumulado mensual.",
      "Solo pago presencial en surtidor o caja.",
    ],
    featuredTag: null,
  },
  {
    id: "itau-latam",
    providerSlug: "itau",
    bankName: "Itaú",
    merchantName: "Latam",
    merchantCanonicalName: "Latam",
    merchantSlug: "latam",
    categoryName: "Viajes",
    title: "15% de descuento en vuelos nacionales Latam pagando con Itaú",
    benefitType: "discount",
    benefitValue: 15,
    benefitValueUnit: "percentage",
    days: ["Todos los días"],
    channel: "online",
    paymentMethods: ["Crédito"],
    capAmount: 50000,
    termsText:
      "Válido en rutas seleccionadas comprando en latam.com. Excluye tasas aeroportuarias.",
    sourceUrl: "https://example.com/itau-latam",
    confidenceScore: 0.89,
    validationStatus: "validated",
    validUntil: "2026-05-20",
    lastUpdated: "2026-04-14",
    summary: "Buen beneficio para ticket medio alto, con tope visible y disponibilidad diaria.",
    conditions: [
      "Aplica solo en tarifas base seleccionadas.",
      "No acumulable con cupones ni campañas flash.",
      "Tope por transacción.",
    ],
    featuredTag: null,
  },
  {
    id: "cencosud-pedidosya",
    providerSlug: "cencosud-scotiabank",
    bankName: "Cencosud Scotiabank",
    merchantName: "PedidosYa",
    merchantCanonicalName: "PedidosYa",
    merchantSlug: "pedidosya",
    categoryName: "Delivery",
    title: "35% de descuento en PedidosYa los fines de semana",
    benefitType: "discount",
    benefitValue: 35,
    benefitValueUnit: "percentage",
    days: ["Sábado", "Domingo"],
    channel: "online",
    paymentMethods: ["Crédito"],
    capAmount: 9000,
    termsText:
      "Válido con cupón bancario en cuentas seleccionadas. Puede requerir monto mínimo.",
    sourceUrl: "https://example.com/cencosud-pedidosya",
    confidenceScore: 0.78,
    validationStatus: "needs_review",
    validUntil: "2026-04-28",
    lastUpdated: "2026-04-10",
    summary: "Atractivo en porcentaje, pero con menor certeza por cambios frecuentes de cupón y stock.",
    conditions: [
      "Requiere ingresar cupón dentro de la app.",
      "Monto mínimo de compra sujeto a campaña.",
      "Puede variar por ciudad o por comercio.",
    ],
    featuredTag: null,
  },
  {
    id: "tenpo-easy",
    providerSlug: "tenpo",
    bankName: "Tenpo",
    merchantName: "Easy",
    merchantCanonicalName: "Easy",
    merchantSlug: "easy",
    categoryName: "Hogar",
    title: "20% de cashback en Easy pagando con tarjeta Tenpo",
    benefitType: "cashback",
    benefitValue: 20,
    benefitValueUnit: "percentage",
    days: ["Martes"],
    channel: "online",
    paymentMethods: ["Prepago"],
    capAmount: 15000,
    termsText:
      "Cashback abonado en la billetera Tenpo en hasta 7 días hábiles. Aplica en easy.cl.",
    sourceUrl: "https://example.com/tenpo-easy",
    confidenceScore: 0.84,
    validationStatus: "monitoring",
    validUntil: "2026-06-15",
    lastUpdated: "2026-04-09",
    summary: "Buena alternativa fintech para compras planificadas de hogar hechas online.",
    conditions: [
      "No aplica en marketplace ni despacho express.",
      "Tope mensual de cashback.",
      "Debe pagarse con tarjeta Tenpo activada.",
    ],
    featuredTag: null,
  },
  {
    id: "santander-jumbo",
    providerSlug: "santander",
    bankName: "Santander",
    merchantName: "Jumbo",
    merchantCanonicalName: "Jumbo",
    merchantSlug: "jumbo",
    categoryName: "Supermercados",
    title: "20% de descuento en Jumbo con WorldMember Santander",
    benefitType: "discount",
    benefitValue: 20,
    benefitValueUnit: "percentage",
    days: ["Viernes"],
    channel: "presencial",
    paymentMethods: ["Crédito"],
    capAmount: 18000,
    termsText:
      "Beneficio sujeto a segmento de tarjeta y locales adheridos.",
    sourceUrl: "https://example.com/santander-jumbo",
    confidenceScore: 0.81,
    validationStatus: "monitoring",
    validUntil: "2026-05-30",
    lastUpdated: "2026-04-12",
    summary: "Buena alternativa de supermercado para clientes premium de Santander.",
    conditions: [
      "Solo tarjetas WorldMember o superiores.",
      "No acumulable con otros descuentos de caja.",
      "Tope mensual por cliente.",
    ],
    featuredTag: null,
  },
  {
    id: "bci-pedidosya",
    providerSlug: "bci",
    bankName: "Bci",
    merchantName: "PedidosYa",
    merchantCanonicalName: "PedidosYa",
    merchantSlug: "pedidosya",
    categoryName: "Delivery",
    title: "40% de descuento en PedidosYa con MACH/Bci",
    benefitType: "discount",
    benefitValue: 40,
    benefitValueUnit: "percentage",
    days: ["Jueves"],
    channel: "online",
    paymentMethods: ["Débito", "Prepago"],
    capAmount: 7000,
    termsText:
      "Aplica con cupón semanal y medios de pago inscritos en la app.",
    sourceUrl: "https://example.com/bci-pedidosya",
    confidenceScore: 0.87,
    validationStatus: "validated",
    validUntil: "2026-05-08",
    lastUpdated: "2026-04-14",
    summary: "Fuerte para consumo recurrente, especialmente si ya usas MACH como medio principal.",
    conditions: [
      "Cupón válido una vez por semana.",
      "Monto mínimo según campaña.",
      "No aplica a propinas ni costos de servicio.",
    ],
    featuredTag: null,
  },
  {
    id: "banco-chile-latam",
    providerSlug: "banco-de-chile",
    bankName: "Banco de Chile",
    merchantName: "Latam",
    merchantCanonicalName: "Latam",
    merchantSlug: "latam",
    categoryName: "Viajes",
    title: "12 cuotas sin interés en Latam con Banco de Chile",
    benefitType: "installments",
    benefitValue: 12,
    benefitValueUnit: "months",
    days: ["Todos los días"],
    channel: "online",
    paymentMethods: ["Crédito"],
    capAmount: null,
    termsText:
      "Promoción válida en pasajes seleccionados, pagando en el sitio oficial de Latam.",
    sourceUrl: "https://example.com/bchile-latam",
    confidenceScore: 0.9,
    validationStatus: "validated",
    validUntil: "2026-06-30",
    lastUpdated: "2026-04-08",
    summary: "Menos agresivo en precio directo, pero muy potente para financiar compras de ticket alto.",
    conditions: [
      "Solo tarjetas de crédito participantes.",
      "No reduce precio, mejora financiamiento.",
      "Sujeto a stock de vuelos y rutas.",
    ],
    featuredTag: null,
  },
  {
    id: "falabella-cruz-verde",
    providerSlug: "banco-falabella",
    bankName: "Banco Falabella",
    merchantName: "Cruz Verde",
    merchantCanonicalName: "Cruz Verde",
    merchantSlug: "cruz-verde",
    categoryName: "Farmacias",
    title: "35% de descuento en Cruz Verde con CMR Débito",
    benefitType: "discount",
    benefitValue: 35,
    benefitValueUnit: "percentage",
    days: ["Domingo"],
    channel: "presencial",
    paymentMethods: ["Débito"],
    capAmount: 10000,
    termsText:
      "Válido para compras en local presentando medio de pago adherido.",
    sourceUrl: "https://example.com/falabella-cruzverde",
    confidenceScore: 0.74,
    validationStatus: "needs_review",
    validUntil: "2026-04-27",
    lastUpdated: "2026-04-07",
    summary: "Beneficio relevante, aunque con señal de revisión por cambios recientes en cobertura.",
    conditions: [
      "Aplica solo domingos.",
      "Excluye productos con precio convenio.",
      "Revisar locales participantes antes de comprar.",
    ],
    featuredTag: null,
  },
]
